"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require('dotenv').load({ silent: true });
const { NAME = 'microsoft-academic-graph', KAFKA_ADDRESS = 'localhost:9092', OUTPUT_TOPIC = 'update_requests', MAG_EVALUATE_URL = 'https://westus.api.cognitive.microsoft.com/academic/v1.0/evaluate', MAG_API_KEY, } = process.env;
exports.NAME = NAME;
exports.KAFKA_ADDRESS = KAFKA_ADDRESS;
exports.OUTPUT_TOPIC = OUTPUT_TOPIC;
exports.MAG_EVALUATE_URL = MAG_EVALUATE_URL;
exports.MAG_API_KEY = MAG_API_KEY;
const START_PAGE = parseInt(process.env.START_PAGE) || 1;
exports.START_PAGE = START_PAGE;
const END_PAGE = parseInt(process.env.END_PAGE) || Infinity;
exports.END_PAGE = END_PAGE;
const PAGE_SIZE = parseInt(process.env.PAGE_SIZE) || 100;
exports.PAGE_SIZE = PAGE_SIZE;
